myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
# from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.aboutpage ),
    path('posts/', include('posts.urls') ),
    path('user/', include('user.urls') ),
    
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='list'),   
    path('new-post/', views.post_new, name='new-post'),   
    path('<slug:slug>', views.post_page, name='page'),   
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register_view,name='register'),     
    path('login/', views.login_view,name='login'),     
    path('logout/', views.logout_view,name='logout'),     
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    
    def __str__(self):
        return self.title

user/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms 
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title','body','slug','banner']

myproject/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('hello world, welcome to the home page')
    return render(request, 'home.html')

def aboutpage(request):
    # return HttpResponse('welcome to the about page')
    return render(request, 'about.html')

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms
# from django.http import HttpResponse

# Create your views here.
def post_list(request):
    posts = Post.objects.all().order_by('-date')
    return render( request, 'posts/posts_list.html', {'posts': posts})

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render( request, 'posts/post_page.html', {'post': post})
    # return HttpResponse(slug)
 
@login_required(login_url="/user/login")    
def post_new(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)  
            newpost.author = request.user
            newpost.save()
            return redirect('posts:list')
    else:   
     form = forms.CreatePost()
    return render(request, 'posts/post_new.html', {'form':form})

    

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("posts:list")
    else:
        form = UserCreationForm()    
    return render(request,'user/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
       form = AuthenticationForm(data=request.POST)
       if form.is_valid():
           # login here
           login(request, form.get_user())
           if 'next' in request.POST:
               return redirect(request.POST.get('next'))
           else:
            return redirect("posts:list")
    else:
        form = AuthenticationForm()
    return render(request,'user/login.html', {'form': form})  

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect("posts:list")
              

posts/templates/posts/post_new.html
{% extends "layout.html" %}

{% block title  %}
{{ post.title}}
{% endblock  %}

{% block content %}
<section>
 <h1>New Post</h1>
 <form action="{% url "posts:new-post" %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form }}
      <button>submit</button>
 </form>
</section>  
{% endblock  %}

posts/templates/posts/post_page.html
{% extends "layout.html" %}

{% block title  %}
{{ post.title}}
{% endblock  %}

{% block content %}
<article>
   <img 
   class="banner"
   src="{{post.banner.url}}"
    alt="{{post.title}}">

   <h1>{{ post.title}}</h1>
   <p class="date">
    {{ post.date}}
   </p>
   <p class="body">
    {{ post.body}}
   </p>
</article>
{% endblock  %}

posts/templates/posts/posts_list.html
{% extends "layout.html" %}

{% block title  %}
Posts 
{% endblock  %}

{% block content %}
<section>
   <h1 class="title">Posts</h1> 
    
   {% for post in posts %}
    <article class="post">
        <h2>
        <a href="{% url 'posts:page' slug=post.slug %}">
          {{ post.title}}
        </a>
           
        </h2>
        <p class="date">{{ post.date}} by {{ post.author}}</p>
        <p class="body">{{ post.body}}</p>
    </article>
   {% endfor%}

</section>
{% endblock  %}

templates/about.html
{% extends "layout.html" %}

{% block title  %}
Home 
{% endblock  %}

{% block content %}
<h1>About</h1>
<p>go back to the <a href="/">home</a> page</p>
{% endblock  %}

templates/home.html
{% extends "layout.html" %}

{% block title  %}
Home 
{% endblock  %}

{% block content %}
<h1>Home</h1>
<p>check out the <a href="/about">about</a> page</p>
{% endblock  %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>
        {% block title%}
          Posts App
        {% endblock%}
    </title>
</head>
<body>
    <nav>
        <a href="/" title="home">Home🏠</a>|
        <a href="/about" title="about">About😎</a>|
        {% if user.is_authenticated %}
        <a href="{% url 'posts:list' %}" title="posts">Posts📰</a>|
        <a href="{% url 'posts:new-post' %}" title="create new post">create🖋</a>|
         <form class="logout" action="{% url 'user:logout' %}" method="post">
            {% csrf_token %}
            <button class="logout-button" arial-label="this is a user logout">logout</button>
        </form>
        {% else %}
        <a href="{% url 'user:register' %}" title="registration">Sign up🚀</a>|
        <a href="{% url 'user:login' %}" title="sign in">Login🔓</a>|
        {% endif %}
       
    </nav>
    <main>
        {% block content %}
        Page is currently under maintenance...
        {% endblock %}
    </main>
</body>
</html>

user/templates/user/login.html
{% extends "layout.html" %}

{% block title  %}
login
{% endblock  %}

{% block content %}
<h1>login</h1>
<form action="{% url 'user:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {%  if request.GET.next %}
       <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}   
    <button type="submit">submit</button>
</form>
{% endblock  %}

user/templates/user/register.html
{% extends "layout.html" %}

{% block title  %}
register 
{% endblock  %}

{% block content %}
<h1>Register</h1>
<form action="{% url 'user:register' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">submit</button>
</form>
{% endblock  %}